[package]
name = "oculussdk"
version = "0.1.0"
authors = ["Nanopro <nanopro1g@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oculussdk-sys = "0.1.0"
libc = "0.2"
ash = "0.29"